name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /usr/share/nginx/html
            git reset --hard
            git pull origin main
            npm ci || npm install
            npm run build
            sudo rm -rf /usr/share/nginx/html/*.html /usr/share/nginx/html/assets
            sudo cp -r dist/* /usr/share/nginx/html/
            sudo systemctl restart nginx
